### ISSUE TITLE
Repeat foreach array help please ?

### ISSUE THREAD

**Issue by hassantest86** [LaravelDaily/Livewire-Parent-Child-Master-Detail#2]
Thank you for  help to How to select dropdown and add more input .
i wish you more learning

**Comment by PovilasKorop** [comment]
@hassantest86 sorry it's not a thing I could answer in a short Github comment, it would require spending a few hours to re-build this demo-project for being re-usable. Currently, I'm not planning any work on it, focused on other projects, sorry.
